### ISSUE TITLE
docker-latest still use old path/naming for loopback

### ISSUE THREAD

**Issue by ghost** [lsm5/docker-latest#5]
For loopback,

`# docker-latest info`
Pool Name: docker-8:1-20801856-pool
Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata

For thinp and overlay, both only create files under /var/lib/docker/ instead of /var/lib/docker-latest/ .

Someone mentioned that the docker-latest binary needs to be modified to use the right ones.

**Comment by lsm5** [comment]
added `-g /var/lib/docker-latest` as argument to docker daemon in unitfile

**Comment by rhvgoyal** [comment]
@lsm5, it might be better to modify default in code. If somebody modifies unit file and removes it, then it goes back to using /var/lib/docker which is unexpected.

**Comment by lsm5** [comment]
On Mon, Apr 11, 2016 at 12:20:23PM -0700, Vivek Goyal wrote:

> @lsm5, it might be better to modify default in code. If somebody modifies unit file and removes it, then it goes back to using /var/lib/docker which is unexpected.

can't we just say PEBKAC error and shame them? :D :D

jokes apart, maybe we could just comment inside the unitfile saying DO NOT
REMOVE IT or whatever?

I guess patching this on @projectatomic/docker just to suit
the new package name would mean a new branch? unless it's trivial to do this
in docker code itself. (no idea yet)

> ---
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/lsm5/docker-latest/issues/5#issuecomment-208510765

## 

Lokesh
Freenode: lsm5
GPG: 0xC7C3A0DD
